//
//  Activity.swift
//  Wegaut
//
//  Created by Felipe Ortega on 11/22/18.
//  Copyright © 2018 Wegaut. All rights reserved.
//

import UIKit

enum activityType {
    
    case newFollower
    case newFollowing
    case newLevel
    case favouritedEvent
    case goingEvent
    case sharedEvent
}

struct Activity {
    
    var actTitle: String
    var actType: activityType
    var actUser: User
    var actEvent: Event?
    var actDate: String
    
    static func getActivities()-> [Activity] {
        
        return [Activity(actTitle: "",
                         actType: activityType.goingEvent,
                         actUser: User(usName: "Emma Roberts",
                                       usEmail: "example@example.com",
                                       usFirstName: "Emma",
                                       usFathersLastName: "Roberts",
                                       usMothersLastName: "Perez",
                                       usProfileImageURL: "https://m.media-amazon.com/images/M/MV5BMTQ4Njg2NTA4MF5BMl5BanBnXkFtZTgwNjAxNjQ0MDI@._V1_.jpg",
                                       usBirthdate: Date(),
                                       usDescription: "Lorem ipsum",
                                       usWegautLevel: Level.noob,
                                       usFollowers: [],
                                       usFollowing: [],
                                       usCreatedEvents: [],
                                       usAssistingEvents: [],
                                       usFavouriteEvents: [],
                                       usSharedEvents: [],
                                       usActivities: [],
                                       usTags: []),
                         actEvent: Event(eveImageURL: "Concurso de videojuegos",
                                         eveName: "Concurso de videojuegos",
                                         evePlace: "Cinemex Antara",
                                         eveAddress: "Ejercito Nacional No. 843 - B Col. Granada, 11520 Miguel Hidalgo, CDMX",
                                         eveDate: "13/09/2018",
                                         eveSchedule: "03:02 PM",
                                         eveAssitantsType: AssistantType.byInvite,
                                         evePrice: "General $900 | VIP $1,250",
                                         eveDescription: "Concurso de videojuegos", eveStatus: true,
                                         eveTags: [],
                                         eveAssitants: [],
                                         evePublications: Publication.getPublications(),
                                         eveComments: [],
                                         eveMultimedia: [],
                                         eveOrganizers: [Organizer(orgName: "Sony Pictures",
                                                                   orgImageURL: "N/A",
                                                                   orgLocalImage: UIImage())],
                                         eveSponsorships: [Sponsorship(spoName: "Cinemex",
                                                                       spoImageURL: "N/A",
                                                                       spoLocalImage: UIImage()),
                                                           Sponsorship(spoName: "Nike",
                                                                       spoImageURL: "N/A",
                                                                       spoLocalImage: UIImage())],
                                         eveAssistants: [],
                                         eveUserFavorited: [],
                                         eveShared: [],
                                         eveCheckIns: [],
                                         eveFollowers: []),
                         actDate: "03:02 PM | 13/09/2018"),
                Activity(actTitle: "",
                         actType: activityType.newFollower,
                         actUser: User(usName: "Emma Roberts",
                                       usEmail: "example@example.com",
                                       usFirstName: "Emma",
                                       usFathersLastName: "Roberts",
                                       usMothersLastName: "Perez",
                                       usProfileImageURL: "https://m.media-amazon.com/images/M/MV5BMTQ4Njg2NTA4MF5BMl5BanBnXkFtZTgwNjAxNjQ0MDI@._V1_.jpg",
                                       usBirthdate: Date(),
                                       usDescription: "Lorem ipsum",
                                       usWegautLevel: Level.noob,
                                       usFollowers: [],
                                       usFollowing: [],
                                       usCreatedEvents: [],
                                       usAssistingEvents: [],
                                       usFavouriteEvents: [],
                                       usSharedEvents: [],
                                       usActivities: [],
                                       usTags: []),
                         actEvent: Event(eveImageURL: "Concurso de videojuegos",
                                         eveName: "Concurso de videojuegos",
                                         evePlace: "Cinemex Antara",
                                         eveAddress: "Ejercito Nacional No. 843 - B Col. Granada, 11520 Miguel Hidalgo, CDMX",
                                         eveDate: "13/09/2018",
                                         eveSchedule: "03:02 PM",
                                         eveAssitantsType: AssistantType.byInvite,
                                         evePrice: "General $900 | VIP $1,250",
                                         eveDescription: "Concurso de videojuegos", eveStatus: true,
                                         eveTags: [],
                                         eveAssitants: [],
                                         evePublications: Publication.getPublications(),
                                         eveComments: [],
                                         eveMultimedia: [],
                                         eveOrganizers: [Organizer(orgName: "Sony Pictures",
                                                                   orgImageURL: "N/A",
                                                                   orgLocalImage: UIImage())],
                                         eveSponsorships: [Sponsorship(spoName: "Cinemex",
                                                                       spoImageURL: "N/A",
                                                                       spoLocalImage: UIImage()),
                                                           Sponsorship(spoName: "Nike",
                                                                       spoImageURL: "N/A",
                                                                       spoLocalImage: UIImage())],
                                         eveAssistants: [],
                                         eveUserFavorited: [],
                                         eveShared: [],
                                         eveCheckIns: [],
                                         eveFollowers: []),
                         actDate: "03:02 PM | 13/09/2018"),
                Activity(actTitle: "Master Chief Class",
                         actType: activityType.sharedEvent,
                         actUser: User(usName: "Emma Watson",
                                       usEmail: "example@example.com",
                                       usFirstName: "Emma",
                                       usFathersLastName: "Watson",
                                       usMothersLastName: "Perez",
                                       usProfileImageURL: "https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cg_face%2Cq_auto:good%2Cw_300/MTQzMzAxODc2MTU3MjYxMzgz/emma-watson_gettyimages-619546914jpg.jpg",
                                       usBirthdate: Date(),
                                       usDescription: "Lorem ipsum",
                                       usWegautLevel: Level.noob,
                                       usFollowers: [],
                                       usFollowing: [],
                                       usCreatedEvents: [],
                                       usAssistingEvents: [],
                                       usFavouriteEvents: [],
                                       usSharedEvents: [],
                                       usActivities: [],
                                       usTags: []),
                         actEvent: Event(eveImageURL: "Master Chief Class",
                                         eveName: "Master Chief Class",
                                         evePlace: "Cinemex Antara",
                                         eveAddress: "Ejercito Nacional No. 843 - B Col. Granada, 11520 Miguel Hidalgo, CDMX",
                                         eveDate: "13/09/2018",
                                         eveSchedule: "03:02 PM",
                                         eveAssitantsType: AssistantType.byInvite,
                                         evePrice: "General $900 | VIP $1,250",
                                         eveDescription: "Master Chief Class", eveStatus: true,
                                         eveTags: [],
                                         eveAssitants: [],
                                         evePublications: Publication.getPublications(),
                                         eveComments: [],
                                         eveMultimedia: [],
                                         eveOrganizers: [Organizer(orgName: "Sony Pictures",
                                                                   orgImageURL: "N/A",
                                                                   orgLocalImage: UIImage())],
                                         eveSponsorships: [Sponsorship(spoName: "Cinemex",
                                                                       spoImageURL: "N/A",
                                                                       spoLocalImage: UIImage()),
                                                           Sponsorship(spoName: "Nike",
                                                                       spoImageURL: "N/A",
                                                                       spoLocalImage: UIImage())],
                                         eveAssistants: [],
                                         eveUserFavorited: [],
                                         eveShared: [],
                                         eveCheckIns: [],
                                         eveFollowers: []),
                         actDate: "03:02 PM | 13/09/2018"),
                Activity(actTitle: "¡Felicidades!",
                         actType: activityType.newLevel,
                         actUser: User.getUserData(),
                         actEvent: nil,
                         actDate: "03:02 PM | 12/09/2018"),
                Activity(actTitle: "Concurso de videojuegos",
                         actType: activityType.sharedEvent,
                         actUser: User(usName: "Emma Roberts",
                                       usEmail: "example@example.com",
                                       usFirstName: "Emma",
                                       usFathersLastName: "Roberts",
                                       usMothersLastName: "Perez",
                                       usProfileImageURL: "https://m.media-amazon.com/images/M/MV5BMTQ4Njg2NTA4MF5BMl5BanBnXkFtZTgwNjAxNjQ0MDI@._V1_.jpg",
                                       usBirthdate: Date(),
                                       usDescription: "Lorem ipsum",
                                       usWegautLevel: Level.noob,
                                       usFollowers: [],
                                       usFollowing: [],
                                       usCreatedEvents: [],
                                       usAssistingEvents: [],
                                       usFavouriteEvents: [],
                                       usSharedEvents: [],
                                       usActivities: [],
                                       usTags: []),
                         actEvent: Event(eveImageURL: "Concurso de videojuegos",
                                         eveName: "Concurso de videojuegos",
                                         evePlace: "Cinemex Antara",
                                         eveAddress: "Ejercito Nacional No. 843 - B Col. Granada, 11520 Miguel Hidalgo, CDMX",
                                         eveDate: "13/09/2018",
                                         eveSchedule: "03:02 PM",
                                         eveAssitantsType: AssistantType.byInvite,
                                         evePrice: "General $900 | VIP $1,250",
                                         eveDescription: "Concurso de videojuegos", eveStatus: true,
                                         eveTags: [],
                                         eveAssitants: [],
                                         evePublications: Publication.getPublications(),
                                         eveComments: [],
                                         eveMultimedia: [],
                                         eveOrganizers: [Organizer(orgName: "Sony Pictures",
                                                                   orgImageURL: "N/A",
                                                                   orgLocalImage: UIImage())],
                                         eveSponsorships: [Sponsorship(spoName: "Cinemex",
                                                                       spoImageURL: "N/A",
                                                                       spoLocalImage: UIImage()),
                                                           Sponsorship(spoName: "Nike",
                                                                       spoImageURL: "N/A",
                                                                       spoLocalImage: UIImage())],
                                         eveAssistants: [],
                                         eveUserFavorited: [],
                                         eveShared: [],
                                         eveCheckIns: [],
                                         eveFollowers: []),
                         actDate: "03:02 PM | 12/09/2018")]
    }
}
