# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

target 'Wegaut' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wegaut

    pod 'BRCountDownView'
    pod 'Colours'
    pod 'IQKeyboardManager'
    pod 'ReachabilitySwift'
    pod 'SDWebImage'

  target 'WegautTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WegautUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
