//
//  Event.swift
//  wegaut
//
//  Created by Felipe Ortega on 6/11/18.
//  Copyright © 2018 InGenious. All rights reserved.
//

import UIKit

struct Event {
    
    var eveImageURL: String
    var eveIsFavorite: Bool
    var eveName: String
    var eveDescription: String
    var evePlace: String
    var eveAddress: String
    var eveDate: String
    var eveSchedule: String
    var eveTags: [String]
    var eveAssitants: String
    var eveOrganizers: [Organizer]
    var eveSponsorships: [Sponsorship]
    var eveURL: String
    var eveStatus: Bool
    var evePublications: [Publication]
    var eveComments: [Comment]
    var eveAssistants: Int
    var eveCheckIns: Int
    var eveFollowers: Int
    
    static func getEvents()->[Event]{
        
        return [Event(eveImageURL: "Sicario",
                      eveIsFavorite: true,
                      eveName: "Sicario 2, Alfombra Roja",
                      eveDescription: "Premier Sicario 2",
                      evePlace: "Cinemex Antara",
                      eveAddress: "Ejercito Nacional No. 843 - B Col. Granada, 11520 Miguel Hidalgo, CDMX",
                      eveDate: "Lunes 11 de Junio de 2018",
                      eveSchedule: "7 pm - 9pm",
                      eveTags: ["Entretenimiento, Cine"],
                      eveAssitants: "Evento público, invitaciones de usuario corporativo",
                      eveOrganizers: [Organizer(orgName: "Sony Pictures",
                                                   orgImageURL: "N/A",
                                                   orgLocalImage: UIImage())],
                      eveSponsorships: [Sponsorship(spoName: "Cinemex",
                                                    spoImageURL: "N/A",
                                                    spoLocalImage: UIImage()),
                                        Sponsorship(spoName: "Nike",
                                                    spoImageURL: "N/A",
                                                    spoLocalImage: UIImage())],
                      eveURL: "http://www.sonypictures.com.mx/",
                      eveStatus: true,
                      evePublications: Publication.getPublications(),
                      eveComments: Comment.getcomments(),
                      eveAssistants: 160,
                      eveCheckIns: 97,
                      eveFollowers: 10000),
                Event(eveImageURL: "Increibles",
                      eveIsFavorite: false,
                      eveName: "Los Increíbles 2 - Premiere México",
                      eveDescription: "Premier Los Increíbles 2",
                      evePlace: "Cinepolis Universidad",
                      eveAddress: "Av. Universidad 1000, Sta Cruz Atoyac, 03310 Ciudad de México, CDMX",
                      eveDate: "Jueves 14 de Junio de 2018",
                      eveSchedule: "7 pm - 9pm",
                      eveTags: ["Entretenimiento, Cine"],
                      eveAssitants: "Evento público, invitaciones de usuario corporativo",
                      eveOrganizers: [Organizer(orgName: "Disney",
                                                orgImageURL: "N/A",
                                                orgLocalImage: UIImage())],
                      eveSponsorships: [Sponsorship(spoName: "Cinemex",
                                                    spoImageURL: "N/A",
                                                    spoLocalImage: UIImage())],
                      eveURL: "http://disneylatino.com/",
                      eveStatus: false,
                      evePublications: [],
                      eveComments: Comment.getcomments(),
                      eveAssistants: 160,
                      eveCheckIns: 97,
                      eveFollowers: 10000),
                Event(eveImageURL: "Tangueros",
                      eveIsFavorite: false,
                      eveName: "Tangueros",
                      eveDescription: "Premier Tangueros",
                      evePlace: "Lunario del Auditorio Nacional",
                      eveAddress: "Paseo de la Reforma 50, Miguel Hidalgo, 11580 Ciudad de México, CDMX",
                      eveDate: "Jueves 12 de Julio de 2018",
                      eveSchedule: "5 pm",
                      eveTags: ["Baile, Entretenimiento, Teatro"],
                      eveAssitants: "Evento público, invitaciones de usuario corporativo",
                      eveOrganizers: [Organizer(orgName: "Ocesa",
                                                orgImageURL: "N/A",
                                                orgLocalImage: UIImage())],
                      eveSponsorships: [Sponsorship(spoName: "Citibanamex",
                                                    spoImageURL: "N/A",
                                                    spoLocalImage: UIImage())],
                      eveURL: "http://www.ocesa.com.mx/",
                      eveStatus: false,
                      evePublications: [],
                      eveComments: Comment.getcomments(),
                      eveAssistants: 160,
                      eveCheckIns: 97,
                      eveFollowers: 10000),
                Event(eveImageURL: "Miserables",
                      eveIsFavorite: true,
                      eveName: "Los Miserables",
                      eveDescription: "Adaptación de la famosa obra ahora en México",
                      evePlace: "Teatro Telcel",
                      eveAddress: "Miguel de Cervantes Saavedra 386, Ampliación Granada, 11529 Ciudad de México, CDMX",
                      eveDate: "Viernes, Sábado y Domingo",
                      eveSchedule: "Múltiples horarios",
                      eveTags: ["Entretenimiento, Teatro"],
                      eveAssitants: "Evento público, invitaciones de usuario corporativo",
                      eveOrganizers: [Organizer(orgName: "Citibanamex",
                                                orgImageURL: "N/A",
                                                orgLocalImage: UIImage())],
                      eveSponsorships: [Sponsorship(spoName: "Ocesa",
                                                    spoImageURL: "N/A",
                                                    spoLocalImage: UIImage())],
                      eveURL: "http://www.losmiserables.mx/teatro-telcel/#",
                      eveStatus: false,
                      evePublications: [],
                      eveComments: Comment.getcomments(),
                      eveAssistants: 160,
                      eveCheckIns: 97,
                      eveFollowers: 10000),
                Event(eveImageURL: "Shakira",
                      eveIsFavorite: true,
                      eveName: "Shakira",
                      eveDescription: "EL DORADO WORLD TOUR",
                      evePlace: "Estadio Azteca",
                      eveAddress: "Calzada de Tlalpan #3665 Col. Santa Úrsula Coapa, Del. Coyoacán, México, DF 04980",
                      eveDate: "Jueves 11 de Octubre de 2018",
                      eveSchedule: "8: 30 pm",
                      eveTags: ["Conciertos, Entretenimiento, Música"],
                      eveAssitants: "Evento público, invitaciones de usuario corporativo",
                      eveOrganizers: [Organizer(orgName: "Citibanamex",
                                                orgImageURL: "N/A",
                                                orgLocalImage: UIImage())],
                      eveSponsorships: [Sponsorship(spoName: "Ocesa",
                                                    spoImageURL: "N/A",
                                                    spoLocalImage: UIImage())],
                      eveURL: "http://www.mexicoboletos.com.mx/boletos-shakira?gclid=Cj0KCQjwvqbaBRCOARIsAD9s1XA5k_45fq-w3KI58ld8m4hVU_hnXjQpobm8Uyd1WHdjHhKFNVgMKBUaAnVAEALw_wcB",
                      eveStatus: false,
                      evePublications: [],
                      eveComments: Comment.getcomments(),
                      eveAssistants: 160,
                      eveCheckIns: 97,
                      eveFollowers: 10000),
                Event(eveImageURL: "Comedy",
                      eveIsFavorite: true,
                      eveName: "Comedy Central Fest",
                      eveDescription: "Ven a reírte con nosotros y los mejores standuperos de México",
                      evePlace: "Colonia Condesa",
                      eveAddress: "Av. Juan Escutia 4, Condesa, CDMX",
                      eveDate: "2, 3 y 4 de Mayo de 2018",
                      eveSchedule: "8 pm",
                      eveTags: ["Comedia, Entretenimiento, Teatro"],
                      eveAssitants: "Evento público, invitaciones de usuario corporativo",
                      eveOrganizers: [Organizer(orgName: "Citibanamex",
                                                orgImageURL: "N/A",
                                                orgLocalImage: UIImage())],
                      eveSponsorships: [Sponsorship(spoName: "Comedy Central",
                                                    spoImageURL: "N/A",
                                                    spoLocalImage: UIImage())],
                      eveURL: "http://www.comedycentralfest.com.mx/#",
                      eveStatus: false,
                      evePublications: [],
                      eveComments: Comment.getcomments(),
                      eveAssistants: 160,
                      eveCheckIns: 97,
                      eveFollowers: 10000),
                Event(eveImageURL: "Nike",
                      eveIsFavorite: false,
                      eveName: "Nike Run MX",
                      eveDescription: "Compite contra ti mismo, superate en esta carrera.",
                      evePlace: "Colonia Condesa",
                      eveAddress: "Paseo de la Reforma, CDMX",
                      eveDate: "28 de Mayo de 2018",
                      eveSchedule: "8 pm",
                      eveTags: ["Deportes"],
                      eveAssitants: "Lista de invitados",
                      eveOrganizers: [Organizer(orgName: "Nike",
                                                orgImageURL: "N/A",
                                                orgLocalImage: UIImage())],
                      eveSponsorships: [Sponsorship(spoName: "Ocesa",
                                                    spoImageURL: "N/A",
                                                    spoLocalImage: UIImage())],
                      eveURL: "https://www.runmx.com/#",
                      eveStatus: false,
                      evePublications: [],
                      eveComments: Comment.getcomments(),
                      eveAssistants: 160,
                      eveCheckIns: 97,
                      eveFollowers: 10000)]
    }
}
